Algoritmo "calcule area do terreno"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2022
Var a:inteiro
   // Seção de Declarações das variáveis
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Informe o lado do terreno")
   leia(a)
   escreval("A área do terreno é", a * a)
Fimalgoritmo