Algoritmo "Maior menor igual"


Var
   a,b :inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite a primeira nota")
   leia(a)
   escreval("Digigite a segunda nota")
   leia(b)

   se a=b entao
      escreval("São iguais")
   senao
      se a>b entao
      escreval("A é maior que B")
      senao
         se a<b entao
            escreval("A é menor que B")
         fimse
      fimse
fimse
Fimalgoritmo
